version: '2'
services:
    instamono-app:
        image: instamono
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://instamono-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=instaMono
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    instamono-mongodb:
        extends:
            file: mongodb.yml
            service: instamono-mongodb
